# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsystem',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
